# Matrix Operations & Linear Algebra 
**FIZ353 - Numerical Analysis | 30/10/2020**

Emre S. Tasci <emre.tasci@hacettepe.edu.tr>

# Basic Matrix Operations


In [1]:
import numpy as np
np.random.seed(353) # we are fixing the random seed, 
                    # so you'll get the same "random" numbers
                    # as of this lecture note's

## Defining
### 'numpy' style

In [2]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 'MATLAB' style (not recommended)
Even though they are much easier to define (and afterwards converted to np.arrays), the usage of np.matrix class are disencouraged because:  
`It is no longer recommended to use this class, even for linear algebra. Instead use regular arrays. The class may be removed in the future.` [Source](https://numpy.org/doc/stable/reference/generated/numpy.matrix.html)

In [3]:
MM = np.matrix("1 2 3; 4 5 6; 7,8,9")
MM

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
# either like this:
M = np.array(MM)

# or like this:
M = MM.A

M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Some special matrices
### Zeros

In [5]:
O = np.zeros((3,4))
O

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Ones

In [6]:
L = np.ones((3,4)) * 3.2
L

array([[3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2, 3.2]])

### Identity

In [7]:
I = np.eye(3,4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### Diagonal

In [8]:
D = np.diag((5,3,7,2))
D

array([[5, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 2]])

#### Off-diagonal

In [9]:
# Upper
DU = np.diag((5,3,7,2),1)
DU

array([[0, 5, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0]])

In [10]:
# Lower
DL = np.diag((5,3,7,2),-1)
DL

array([[0, 0, 0, 0, 0],
       [5, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 7, 0, 0],
       [0, 0, 0, 2, 0]])

### Random Matrices

In [11]:
# Uniform distribution [0,1)
R1 = np.random.random((4,5))
R1

array([[0.43618003, 0.26300446, 0.81565745, 0.6808622 , 0.74138771],
       [0.30520115, 0.08876155, 0.7506812 , 0.20489849, 0.26102374],
       [0.43189534, 0.22048083, 0.51118854, 0.14658739, 0.14535176],
       [0.76389177, 0.2915416 , 0.52110675, 0.17400217, 0.69313813]])

In [12]:
# Uniform distribution, integers [a,b)
R2 = np.random.randint(6,10,(4,5))
R2

array([[9, 6, 9, 6, 9],
       [8, 7, 6, 8, 9],
       [6, 9, 6, 6, 9],
       [8, 8, 7, 9, 9]])

## Accessing (getting and setting)

In [13]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
M[2,2]

9

In [15]:
M[2,:]

array([7, 8, 9])

In [16]:
M[:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [17]:
M[:,1] = -1
M

array([[ 1, -1,  3],
       [ 4, -1,  6],
       [ 7, -1,  9]])

## Duplication

When copying an array **object**, be careful that they are not copied over like scalars:

In [18]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
N = M
N

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
M[2,2] = -9
M

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, -9]])

In [21]:
N

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, -9]])

Instead, use the `copy()` method:

In [22]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
N = M.copy()
N

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
M[2,2] = -9
M

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, -9]])

In [25]:
N

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Filtering (Essential!)

In [26]:
M

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, -9]])

In [27]:
M>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True, False]])

In [28]:
# The elements that are greater than 5:
M[M > 5]

array([6, 7, 8])

In [29]:
# The elements that are even:
M[M % 2 == 0]

array([2, 4, 6, 8])

In [30]:
M>=3

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [31]:
M<=8

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [32]:
np.logical_and(M>=3, M<=8)

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [33]:
# The elements that are between 3 and 8 (inclusive):
M[np.logical_and(M>=3, M<=8)]

array([3, 4, 5, 6, 7, 8])

In [34]:
# The elements that are smaller than 3 or greater than 7 (inclusive)
M[np.logical_or(M<=3, M>=7)]

array([ 1,  2,  3,  7,  8, -9])

#### Intersection of two arrays

In [35]:
# Intersection of two arrays:
N = np.random.randint(-5,10,(3,3))
N

array([[ 6,  2, -2],
       [ 1,  5,  1],
       [ 2, -2,  3]])

In [36]:
np.intersect1d(M,N)

array([1, 2, 3, 5, 6])

# Multiplication

In [37]:
M

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, -9]])

## Scalar x Matrix

In [38]:
5.21 * M

array([[  5.21,  10.42,  15.63],
       [ 20.84,  26.05,  31.26],
       [ 36.47,  41.68, -46.89]])

## Matrix x Vector

In [39]:
v = np.array([[9],[8],[7]])
v

array([[9],
       [8],
       [7]])

In [40]:
np.dot(M,v)

array([[ 46],
       [118],
       [ 64]])

In [41]:
v.T # 'T' for "transpose"

array([[9, 8, 7]])

In [42]:
np.dot(v.T,M)

array([[ 90, 114,  12]])

**Be very careful!**

`np.dot(M,v)` **is not equal to** `M*v` and,  
`np.dot(v.T,M)` **is not equal to** `v.T*M`

Multiplying
* a (3x3) matrix with a (3x1) matrix should yield a (3x1) matrix and,
* a (1x3) vector with a (3x3) matrix should yield a (1x3) vector!

Compare the following results with the above ones!

In [43]:
M

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, -9]])

In [44]:
v

array([[9],
       [8],
       [7]])

In [45]:
M*v

array([[  9,  18,  27],
       [ 32,  40,  48],
       [ 49,  56, -63]])

In [46]:
v.T*M

array([[  9,  16,  21],
       [ 36,  40,  42],
       [ 63,  64, -63]])

(These just do <u>element-wise</u> multiplications!)

## Determinant & Inverse of a Square Matrix

In [47]:
M = np.array([[2,1,3],[4,6,3],[7,8,9]])
M

array([[2, 1, 3],
       [4, 6, 3],
       [7, 8, 9]])

* **Determinant**  
  

In [48]:
M_det = np.linalg.det(M)
print("Determinant of M is: {:.3f}".format(M_det))

Determinant of M is: 15.000


* **Inverse**

In [49]:
M_inv = np.linalg.inv(M)
M_inv

array([[ 2.        ,  1.        , -1.        ],
       [-1.        , -0.2       ,  0.4       ],
       [-0.66666667, -0.6       ,  0.53333333]])

In [50]:
np.dot(M,M_inv)

array([[1.00000000e+00, 2.22044605e-16, 0.00000000e+00],
       [8.88178420e-16, 1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [51]:
np.dot(M_inv,M)

array([[ 1.00000000e+00, -1.77635684e-15, -1.77635684e-15],
       [ 8.88178420e-16,  1.00000000e+00,  1.33226763e-15],
       [ 4.44089210e-16,  8.88178420e-16,  1.00000000e+00]])

# Matrices as Operators
Consider a (3x1) vector (let's think it as a *position vector*. It can be multiplied from left by a (3x3) matrix, and the result will be a (3x1) vector. We can interpret this operation as a *transformation operation* on the vector. As, by definition, a vector has a magnitude and a direction, a transformation can change these two properties. First, let's investigate these effects seperately by operating on a 2-dimensional vector, and then we'll combine them.

## Changing a vector's magnitude (Scaling)
This is very straightforward as we can change a vector's magnitude by simply multiplying it with a scalar.

$\vec{v} = 3\hat{\imath}+4\hat{\jmath}$

In [52]:
v = np.array([3,4]) # a 2 dimensional vector
v

array([3, 4])

In [53]:
# It's magnitude:
v_mag = np.linalg.norm(v)
print("The magnitude of vector v: {:}".format(v_mag))

The magnitude of vector v: 5.0


In [54]:
# We could as well have calculated it via Pythagorean Theorem:
v_mag = (v[0]**2 + v[1]**2)**0.5
print("The magnitude of vector v: {:}".format(v_mag))

The magnitude of vector v: 5.0


In [55]:
# or, more practically then the above 
# (for which, we have to enter each dimension exclusively)
# we could (and should) go for direct evaluation:
v_mag = (np.sum(v*v))**0.5
print("The magnitude of vector v: {:}".format(v_mag))

The magnitude of vector v: 5.0


(examine and understand how we have done - this is better than the second solution but using predefined functions such as `norm` is almost always more optimized)

Now that we know our vector's initial magnitude, let's multiply it by a scalar, `s = 2` and check the resultant vector $\vec{r}$'s magnitude:

In [56]:
s = 2
r = 2*v
print(r)

[6 8]


In [57]:
print("The magnitude of vector r: {:}".format(np.linalg.norm(r)))

The magnitude of vector r: 10.0


How can we write this _size change_ operation as a multiplication of a matrix by the vector? It will sound dumb, but we can insert the identity matrix in the middle, as it doesn't change a vector it is being multiplied to, so nothing should change:

$$ s\cdot\vec{v} = \underbrace{s\cdot(\mathbb{1})}_{S}\cdot\vec{v}$$

From here, we can apply the scalar to the identity vector, which will be equal to a diagonal vector with the diagonal values being equal to $s$:

In [58]:
I = np.eye(2,2) # as our vector is 2 dimensional,
                # corresponding identity vector is (2x2)
print(I)

[[1. 0.]
 [0. 1.]]


In [59]:
S = s*I
S

array([[2., 0.],
       [0., 2.]])

The multiplication has now taken the form of a matrix multiplied by a vector:

$$\underbrace{\begin{bmatrix}2 & 0 \\ 0 & 2\end{bmatrix}}_{S}\cdot\underbrace{\begin{bmatrix}3 \\ 4\end{bmatrix}}_{\vec{v}}$$

In [60]:
r = np.dot(S,v)
print(r)

[6. 8.]


In [61]:
print("The magnitude of vector r: {:}".format(np.linalg.norm(r)))

The magnitude of vector r: 10.0


So, in summary, if we change the size of a vector, we just multiply it with a diagonal matrix, whose diagonal elements' values are equal to the ratio of the change of size.

## Rotating a vector
The rotation operator R for a 2D vector is defined as:

$$ R_{\theta} = \begin{pmatrix}\cos\theta & -\sin\theta \\ \sin\theta & \cos\theta\end{pmatrix}$$

where $\theta$ is the rotation angle, counter-clockwise.

So, if we would rotate a $\vec{v}$ vector of, let's say, 5 units long along the positive x-direction by an angle of $90^o$, we would get a vector with the same magnitude, pointing alont the positive y-direction: 

$$R_{90^o}.\vec{v} = R_{90^o}.(5\hat{\imath}) = 5\hat{\jmath}$$

Let's put this in action:

In [62]:
theta = np.deg2rad(90)
R_theta = np.array([[np.cos(theta), -np.sin(theta)],
                    [np.sin(theta),  np.cos(theta)]])
R_theta

array([[ 6.123234e-17, -1.000000e+00],
       [ 1.000000e+00,  6.123234e-17]])

In [63]:
v = np.array([[5],[0]])
v

array([[5],
       [0]])

In [64]:
v_rotated_90 = np.dot(R_theta,v)
v_rotated_90

array([[3.061617e-16],
       [5.000000e+00]])

In [65]:
# Let's rotate this resultant vector once again by 90 degrees:
v_rotated_90_90 = np.dot(R_theta,v_rotated_90)
v_rotated_90_90

array([[-5.000000e+00],
       [ 6.123234e-16]])

We can write the last operation explicitly as:

$$R_{90^o}.\vec{v}' =R_{90^o}.\left(R_{90^o}\vec{v}\right)$$

changing the order of multiplication:

$$R_{90^o}.\vec{v}' =\left(R_{90^o}.R_{90^o}\right)\vec{v} = R_{90^o}^2.\vec{v}$$

In [66]:
R_90_squared = np.dot(R_theta,R_theta)
R_90_squared

array([[-1.0000000e+00, -1.2246468e-16],
       [ 1.2246468e-16, -1.0000000e+00]])

In [67]:
v_rotated_90_90 = np.dot(R_90_squared,v)
v_rotated_90_90

array([[-5.000000e+00],
       [ 6.123234e-16]])

## Transformation Matrix (Scaling & Rotation)
We can rotate a vector, and then change its magnitude, or, we can change its magnitude and then rotate it -- from physical point of view, the order shouldn't matter. And as it turns out perfectly, even though $A\cdot B \ne B\cdot A$ almost always, for these two rotation & scaling operation matrices, both ordering yields the same result (you can easily prove this for two general (2x2) matrices by hand). So, we can write a general transformation matrix $T$ as a multiplication (combination) of the two:

In [68]:
theta = np.deg2rad(30)
R_30 = np.array([[np.cos(theta), -np.sin(theta)],
                    [np.sin(theta),  np.cos(theta)]])
R_30

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [69]:
S_3 = 3*np.eye(2,2)
S_3

array([[3., 0.],
       [0., 3.]])

In [70]:
T = np.dot(R_30,S_3)
T

array([[ 2.59807621, -1.5       ],
       [ 1.5       ,  2.59807621]])

In [71]:
T = np.dot(S_3,R_30)
T

array([[ 2.59807621, -1.5       ],
       [ 1.5       ,  2.59807621]])

What we have ourselves here is a transformation matrix that rotates a vector by $30^o$ and triples its size. Let's roll! 8)

In [72]:
# For our first case, let's transform the unit vector 
# along the positive x-direction:
v = np.array([[1],[0]])
v

array([[1],
       [0]])

In [73]:
vp = np.dot(T,v)
vp

array([[2.59807621],
       [1.5       ]])

In [74]:
# Its size:
np.linalg.norm(vp)

3.0

In [75]:
# We can calculate its angle wrt x-axis by calculating
# the arctan (vp_y/vp_x):
angle_rad = np.arctan(vp[1]/vp[0])
print("The angle in radians: {:}".format(angle_rad))
print("The angle in degrees: {:}".format(np.rad2deg(angle_rad)))

The angle in radians: [0.52359878]
The angle in degrees: [30.]


(For a much more "intelligent" arctan process, I strongly recommend the `arctan2` function, which saves you from further consideration of the quadrants (i.e., Q1 vs. Q3 and Q2 vs. Q4)

In [76]:
angle_rad = np.arctan2(vp[1],vp[0])
print("The angle in radians: {:}".format(angle_rad))
print("The angle in degrees: {:}".format(np.rad2deg(angle_rad)))

The angle in radians: [0.52359878]
The angle in degrees: [30.]


So, the size is indeed tripled and our vector has been rotated by 30 degrees! 8)

In [77]:
## Now let's roll with a random vector:
v = (np.random.rand(1,2)*10).T
v

array([[0.37672523],
       [6.62082483]])

In [78]:
# initial size:
size_before = np.linalg.norm(v)
print("The vector's size is: {:}".format(size_before))

The vector's size is: 6.631534010791827


In [79]:
angle_deg_before = np.rad2deg(np.arctan2(v[1],v[0]))
print("The vector's angle (wrt x-axis) is: {:.3f} degress"
      .format(angle_deg_before[0]))

The vector's angle (wrt x-axis) is: 86.743 degress


In [80]:
# Transform it!
vp = np.dot(T,v)
vp

array([[-8.95247639],
       [17.76649534]])

In [81]:
# Its size after the transformation:
size_after = np.linalg.norm(vp)
print("The vector's size after transformation is: {:}".format(size_after))

The vector's size after transformation is: 19.89460203237548


In [82]:
# The ratios of after/before:
print("The size has changed by a factor of: {:}".format(size_after/size_before))

The size has changed by a factor of: 3.0


In [83]:
# Its angle after the transformation:
angle_deg_after = np.rad2deg(np.arctan2(vp[1],vp[0]))
print("The vector's angle (wrt x-axis) is: {:.3f} degress"
      .format(angle_deg_after[0]))

The vector's angle (wrt x-axis) is: 116.743 degress


In [84]:
# The difference between the final and initial angles:
print("The vector has rotated by {:.3f} degrees"
      .format(angle_deg_after[0] - angle_deg_before[0]))

The vector has rotated by 30.000 degrees


# A practical application
## Definitions
Suppose that we are given a vector $\vec{v}'$ and we are told that this vector has been rotated by an angle of $\theta$ and its magnitude is scaled by a factor of $n$, and we are asked to calculate the initial vector $\vec{v}$. So here is what we have:

$$\vec{v}' = \begin{bmatrix}n & 0 \\ 0 & n\end{bmatrix}\begin{bmatrix}\cos\theta & -\sin\theta \\ \sin\theta & \cos\theta\end{bmatrix}\vec{v}=\underbrace{\begin{bmatrix}n\cos\theta & -n\sin\theta \\ n\sin\theta & n\cos\theta\end{bmatrix}}_{T}\vec{v}$$

To find $\vec{v}$, we would first rotate it (back) _clockwise_ by 30 degrees (i.e., $-30^0$) and then would scale it $\vec{v}'$ by a factor of $\tfrac{1}{3}$. In mathematical representation this would be:

$$\vec{v} = \begin{bmatrix}\tfrac{1}{n} & 0 \\ 0 & \tfrac{1}{n}\end{bmatrix}\begin{bmatrix}\cos{(-\theta)} & -\sin{(-\theta)} \\ \sin{(-\theta)} & \cos{(-\theta)}\end{bmatrix}\vec{v}'=\underbrace{\begin{bmatrix}\tfrac{1}{n}\cos\theta & \tfrac{1}{n}\sin\theta \\ -\tfrac{1}{n}\sin\theta & \tfrac{1}{n}\cos\theta\end{bmatrix}}_{T'}\vec{v}'$$

Let's put some numbers in it, for example $n=3$ & $\theta=30^o$, $\vec{v}' = 1.7942\hat{\imath} + 14.8923\hat{\jmath} $:

In [85]:
n = 3
angle = np.deg2rad(30)
T = np.array([[n*np.cos(angle),-n*np.sin(angle)],[n*np.sin(angle),n*np.cos(angle)]])
T

array([[ 2.59807621, -1.5       ],
       [ 1.5       ,  2.59807621]])

Now let's calculate the reversed (_inverted?_) version from the formula:

In [86]:
n = 1/3
angle = np.deg2rad(-30)
Tp = np.array([[n*np.cos(angle),-n*np.sin(angle)],[n*np.sin(angle),n*np.cos(angle)]])
Tp

array([[ 0.28867513,  0.16666667],
       [-0.16666667,  0.28867513]])

Thus, by multiplying $T'$ with $\vec{v}'$, we get:

In [87]:
vp = np.array([[1.7942],[14.8923]])
vp

array([[ 1.7942],
       [14.8923]])

In [88]:
v = np.dot(Tp,vp)
v

array([[2.99999093],
       [4.00000337]])

which means that, our original vector was: $\vec{v} = 3\hat{\imath}+4{\jmath}$

**Ready for a surprise?**  
Here is the inverse of the transformation matrix, directly calculated by the `linalg.inv()` method:

In [89]:
np.linalg.inv(T)

array([[ 0.28867513,  0.16666667],
       [-0.16666667,  0.28867513]])

We saw it somewhere before, right? ;)

Thus:

$$\begin{align*}T\cdot \vec{v} &= \vec{v}'\\
\underbrace{T^{-1}\cdot T}_{\mathbb{1}}\cdot \vec{v} &=T^{-1}\cdot \vec{v}'\\
\vec{v} &=T^{-1}\cdot \vec{v}'\end{align*}$$

In [90]:
np.dot(np.linalg.inv(T),vp)

array([[2.99999093],
       [4.00000337]])

### Sidenote: Calculating $n$ & $\theta$ from the combined transformation matrix*
_(*As long as we're keeping the 'new coordinates' perpendicular)_

We could have been directly given the transformation matrix T:

In [91]:
T = np.array([[ 2.59807621, -1.5],[ 1.5       ,  2.59807621]])
T

array([[ 2.59807621, -1.5       ],
       [ 1.5       ,  2.59807621]])

and we could have been asked to extract $n$ & $\theta$. What we could have done would be to calculate the determinant of the transformation matrix, which would be:

$$n^2.\cos^2{\theta} + n^2.\sin^2{\theta} \equiv n^2$$

Then, we would divide the matrix by $n$ to get the rotation matrix and thus, the angle:

In [92]:
n = np.sqrt(np.linalg.det(T))
print("The scaling factor is: {:.3f}".format(n))

The scaling factor is: 3.000


In [93]:
R = T/n
R

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [94]:
angle = np.rad2deg(np.arctan2(R[1,0],R[0,0]))
print("The rotation angle is: {:.3f} degrees".format(angle))

The rotation angle is: 30.000 degrees


## Application
**Example** 
$\vec{v}=\begin{pmatrix}v_x\\v_y\end{pmatrix}$ vector is rotated and scaled by a transformation matrix defined as: 

$$T=\begin{bmatrix}2.59807621&-1.5\\1.5 &2.59807621\end{bmatrix}$$


and if the resulting vector $\vec{v}'$ is given as $\vec{v}' = 1.7942\hat{\imath} + 14.8923\hat{\jmath} $, calculate the initial vector $\vec{v}$.

So we can write it as:
$$T\cdot \vec{v}=\vec{v}'$$
$$\begin{bmatrix}2.59807621&-1.5\\1.5 &2.59807621\end{bmatrix}\begin{pmatrix}v_x\\v_y\end{pmatrix}=\begin{pmatrix}1.7942\\14.8923\end{pmatrix}$$

But we have already solved this problem and found the answer to be:

$$\vec{v}=\begin{pmatrix}v_x\\v_y\end{pmatrix}=\begin{pmatrix}3\\4\end{pmatrix} = 3\hat{\imath} + 4\hat{\jmath}$$

How very nice! 8)

Now consider this set of two equations with two unknowns:
$$\begin{gather*}4x - y = 10\\3x + 2y=13\end{gather*}$$

Can we write it as a multiplication of a matrix by a vector like the following?

$$\begin{bmatrix}4&-1\\3&2\end{bmatrix}\begin{bmatrix}x\\y\end{bmatrix} = \begin{bmatrix}10\\13\end{bmatrix}$$

(please verify that, we indeed can...)

So, even though it is a set of 2 equations with two unknowns, we can interpret it as if it is a vector transformation! _(albeit, a transformation, that doesn't keep the angle between the new axes perpendicular)_

Sooooo:

In [95]:
vp = np.array([[10],[13]])
T = np.array([[4,-1],[3,2]])
np.dot(np.linalg.inv(T),vp)

array([[3.],
       [2.]])

We have just solved our set of equations!

(As this solving of linear operations are very common in scientific calculations, there is a direct function called `linalg.solve()` defined for it, i.e.,

In [96]:
np.linalg.solve(T,vp)

array([[3.],
       [2.]])

# Eigenvectors, Eigenvalues


In [97]:
A = np.array([[2,3],[4,5]])
A

array([[2, 3],
       [4, 5]])

$$A\vec{u} = \lambda\mathbb{1}\vec{u}$$
$$\begin{bmatrix}a_{11}&a_{12}\\a_{21}&a_{22}\end{bmatrix}\vec{u} = \begin{bmatrix}\lambda&0\\0&\lambda\end{bmatrix}\vec{u}$$
$$\begin{bmatrix}a_{11}&a_{12}\\a_{21}&a_{22}\end{bmatrix}\vec{u} - \begin{bmatrix}\lambda&0\\0&\lambda\end{bmatrix}\vec{u} = 0$$
$$\begin{bmatrix}a_{11}-\lambda&a_{12}\\a_{21}&a_{22}-\lambda\end{bmatrix}\vec{u} = \begin{pmatrix}0\\0\end{pmatrix}$$

In [98]:
[eigvalues, eigvectors] = np.linalg.eig(A)
print("Eigenvalues: ",eigvalues,"\n-----\nEigenvectors:\n",eigvectors)

Eigenvalues:  [-0.27491722  7.27491722] 
-----
Eigenvectors:
 [[-0.79681209 -0.49436913]
 [ 0.60422718 -0.86925207]]


In [99]:
E1 = eigvectors[:,0]
E2 = eigvectors[:,1]
l1 = eigvalues[0]
l2 = eigvalues[1]

In [100]:
vp1 = np.dot(A,E1)
vp1

array([ 0.21905736, -0.16611246])

In [101]:
np.cross(vp1,E1)

array(5.55111512e-17)

In [102]:
np.dot(vp1,E1)

-0.27491721763537486

In [103]:
-0.79681209* 0.21905736 + 0.60422718 * -0.16611246

-0.2749172161201452

In [104]:
ctheta = np.dot(vp1,E1)/(np.linalg.norm(vp1)*np.linalg.norm(E1) )
np.rad2deg(np.arccos(ctheta))

180.0

In [105]:
vp1 / l1

array([-0.79681209,  0.60422718])

In [106]:
vp1 / E1

array([-0.27491722, -0.27491722])

In [107]:
np.linalg.norm(E1)

1.0

In [108]:
np.diag(eigvalues)

array([[-0.27491722,  0.        ],
       [ 0.        ,  7.27491722]])

## Diagonalization

In [109]:
np.linalg.multi_dot([eigvectors,np.diag(eigvalues),np.linalg.inv(eigvectors)])

array([[2., 3.],
       [4., 5.]])